### ISSUE TITLE
Signet improvements

### ISSUE THREAD

**Issue by openoms** [openoms/joininbox#85]
- [x] edit the signet bitcoin.conf from CONFIG if signet is default (if separate)
- [x] connect to raspiblitz signet node is present
- [x] switch onion directory_nodes when connecting to signet
- [x] keep signet setting on update

**Comment by GordianLN** [comment]
As per https://t.me/joinmarketorg/18220
Confirming that after update of joininbox distro, on pi3, I found out only by chance that the signet configuration had been reset to mainnet.
Since the automation on joininbox is impressive, and holds your hand very much making you lazy, adding a check to keep signet config on update, AND also having the config be updated to use signet directory nodes and commenting mainnet ones, should be implemented, otherwise users expecting everything to works automagically will lower their defenses and just stand there clueless when something doesn't work
